version: 2.1

orbs:
  macos: circleci/macos@2.0.1

jobs:
  voiceover-test:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - macos/add-uitest-permissions
      - macos/add-safari-permissions
      - run:
          name: Add VoiceOver AppleScript DB Entry
          command: sudo bash -c 'echo -n "a" > /private/var/db/Accessibility/.VoiceOverAppleScriptEnabled'
      - run:
          name: Set AppleScript Enabled Default
          command: defaults write com.apple.VoiceOver4/default SCREnableAppleScript -bool true
      - run:
          name: Set Disable Splash Screen Default
          command: defaults write com.apple.VoiceOverTraining doNotShowSplashScreen -bool true
      - run:
          name: VoiceOver Test
          command: osascript ./test.applescript || true
      - store_artifacts:
          path: ./screenshots

workflows:
  version: 2
  voiceover-poc-workflow:
    jobs:
      - voiceover-test
