version: 2.1

jobs:
  voiceover-test:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: Add VoiceOver AppleScript DB Entry
          command: sudo bash -c 'echo -n "a" > /private/var/db/Accessibility/.VoiceOverAppleScriptEnabled'
      - run:
          name: Set System Preferences Default
          command: defaults write com.apple.VoiceOver4/default SCREnableAppleScript 1
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: VoiceOver Test
          command: yarn test

workflows:
  version: 2
  voiceover-poc-workflow:
    jobs:
      - voiceover-test
