version: 2.1

orbs:
  macos: circleci/macos@2.0.1

jobs:
  voiceover-test:
    macos:
      xcode: 12.5.1
    resource_class: medium
    steps:
      - checkout
      - macos/add-uitest-permissions
      - macos/add-safari-permissions
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Enable VoiceOver Automation
          command: npx @guidepup/setup --ci
      - run:
          name: Run VoiceOver Test
          command: yarn test
      - store_artifacts:
          path: "./test-results"

workflows:
  version: 2
  voiceover-poc-workflow:
    jobs:
      - voiceover-test
